name: github actio demo pipeline

#triggre pipeline
on:
  push:
    branches:
       - main

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps: 
      - name: checkout code
        uses: actions/checkout@v2

      - name: print message
        run: echo "wwlcome to gitaction"